"""Create fez_atendimento

Revision ID: c6bd7329ee81
Revises: 
Create Date: 2020-08-20 20:53:22.372518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6bd7329ee81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_adms_saude_id_cidade'), 'adms_saude', ['id_cidade'], unique=False)
    op.add_column('atendimentos', sa.Column('fez_atendimento', mysql.TINYINT(display_width=1), nullable=True))
    op.drop_column('cidades', 'nome')
    op.create_index(op.f('ix_estrategias_saude_familiar_id_cidade'), 'estrategias_saude_familiar', ['id_cidade'], unique=False)
    op.create_index(op.f('ix_pacientes_id_cidade'), 'pacientes', ['id_cidade'], unique=False)
    op.create_index(op.f('ix_tempos_contato_acompanhamento_id_cidade'), 'tempos_contato_acompanhamento', ['id_cidade'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tempos_contato_acompanhamento_id_cidade'), table_name='tempos_contato_acompanhamento')
    op.drop_index(op.f('ix_pacientes_id_cidade'), table_name='pacientes')
    op.drop_index(op.f('ix_estrategias_saude_familiar_id_cidade'), table_name='estrategias_saude_familiar')
    op.add_column('cidades', sa.Column('nome', mysql.VARCHAR(length=60), nullable=False))
    op.drop_column('atendimentos', 'fez_atendimento')
    op.drop_index(op.f('ix_adms_saude_id_cidade'), table_name='adms_saude')
    # ### end Alembic commands ###
